import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Footer} from "../components/Footer";
import {Link} from "../components/Link";
import {Headline} from "../components/Headline";

export　default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline page={"about"}/>

        <Link />

      </main>

      <Footer />
    </div>
  )
}
